### ISSUE TITLE
Создать REST контроллеры

### ISSUE THREAD

**Issue by Kirvolque** [varannteam/varann#10]
Создать два контроллера:
1. Эндпойнт для добавления данных из vcf в базу (post зпапрос).
2. Эндпойнт для поиска вариантов в базе. Должен возвращать INFO поле или VariantDto целиком.

**Comment by tcibinan** [comment]
Можем пока сделать один контроллер с двумя метода по аналогии с #9:
- Первый принимает input stream, содержащий размеченный vcf файл.
- Второй метод принимает и отдает json-ы, по структуре соответствующие описанным в #9.

Как пример, первый метод может использовать через `<input type="file"/>` на html-страничке.

**Comment by step-ponomarev** [comment]
Я сделяль. И я снова удалял форк, надеюсь, это не помешает.

**Comment by tcibinan** [comment]
@step-ponomarev Сделай pull request плз.
