### ISSUE TITLE
Настроить swagger

### ISSUE THREAD

**Issue by tcibinan** [varannteam/varann#12]
Для того чтобы у нас появилась удобная документация апи, а также самый простой клиент приложения, можно попробовать использовать swagger. Эта штука умеет автоматически генерировать html на основе spring контроллеров.

Описание, как swagger конфигурируется для spring boot приложения, можно подглядеть [здесь](https://www.baeldung.com/swagger-2-documentation-for-spring-rest-api).

**Comment by step-ponomarev** [comment]
Сделал! Будет ишью по докеру?)

**Comment by tcibinan** [comment]
@step-ponomarev Отлично, вот https://github.com/varannteam/varann/issues/14.
