### ISSUE TITLE
Написать vcf parser

### ISSUE THREAD

**Issue by Kirvolque** [varannteam/varann#3]
Необходимо:
1. Найти маленький vcf файл.
2. Подтянуть зависимость https://mvnrepository.com/artifact/com.github.samtools/htsjdk
3. Написать парсер принимающий на вход vcf файл и возвращающий `Stream<VariantContext>`.
4. Написать тесты для парсера.

**Comment by tcibinan** [comment]
Добавлю несколько комментов.

Задача сводится к написанию 1 интерфейса и 1 класса, реализующего этот интерфейс. Интерфейс должен содержать всего один метод, который принимает на вход vcf файл (например, InputStream), а на выход возвращает список (например, List или Stream) вариаций.

Работая с файлом, можно, конечно, парсить его руками (резать на строки, разбивать по колонкам), но это слишком муторно и бессмысленно, потому что есть библиотечка htsjdk. Ее нужно подключить к проекту, добавив запись в build.gradle, и использовать для чтения этих самых вариаций.

Для тестирования такого класса не понадобится даже Spring, хватит junit и нескольких маленьких локальных vcf файлов.

**Comment by step-ponomarev** [comment]
Я изменил тип возвращаемого значения `Stream<VariantContext> parse(InputStream inputStream);`
