### ISSUE TITLE
Создать DAO слой для хранения данных из vcf в базе.

### ISSUE THREAD

**Issue by Kirvolque** [varannteam/varann#5]
С помощтю Hibernate необходимо создать энтити Variation и инициализировать базу данных для хранения вариаций.

Необходимые поля:
chrom - text
pos - int
ref - text
alt - text
info - text

**Comment by tcibinan** [comment]
Хочу уточнить, что мы будем использовать Hibernate не на прямую, а через библиотечку [Spring Data JPA](https://spring.io/guides/gs/accessing-data-jpa/), которую нужно будет подключить к проекту.

Целью этой задачи будет описать структуру базы данных (1 таблицы) в виде Entity (java класса с одноименной аннотацией), а также объявить Repository, через который можно сохранять\удалять\искать аннотации.

Важно также, что primary key в нашем случае составной и состоит из полей *chrom, pos, ref и alt*.

**Comment by tcibinan** [comment]
Используем postgresql 11. Можно либо установить локально, либо запускать из докера.
