### ISSUE TITLE
Создать сервис для обработки запросов

### ISSUE THREAD

**Issue by Kirvolque** [varannteam/varann#9]
Сервис должен инжектить парсер и репозиторий.
Должны быть реализованы методы:
1. Для добвления данных из vcf файла в базу (на входе InputStream)
2. Метод для извлечения вариации из базы данных. Должен принимать chrom pos alt ref возвращать VariantDto (конвертировать Entity в DTO).

**Comment by tcibinan** [comment]
Если на выходе json, то пусть может и на входе будет json. Что-нибудь типо `VariantAnnotationRequest`, который уже будет иметь поля *chrom, pos, alt и ref*. Еще можем убрать суффикс *Dto*, потому что он не несет никакой нагрузки.

Итого, нам нужен сервис, который:
- принимает на вход `InputStream`, содержащий проаннотированный vcf файл, и записывает его в базу, используя наработки из #8 и #7.
- принимает на вход `VariantAnnotationRequest`, ищет его в базе используя #7 и возвращает `Variant`.

Нужны как минимум юнит тесты, которые используют моки, например, из библиотеки `mockito`.

**Comment by tcibinan** [comment]
Решено в #11.
